//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckCardStatus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SDProject : DbContext
    {
        public SDProject()
            : base("name=SDProject")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<string> SP_CheckAuthenticateTranscation(string authtoken, string cardNumber, Nullable<int> cvv, Nullable<System.DateTime> dateOfExpiry)
        {
            var authtokenParameter = authtoken != null ?
                new ObjectParameter("authtoken", authtoken) :
                new ObjectParameter("authtoken", typeof(string));
    
            var cardNumberParameter = cardNumber != null ?
                new ObjectParameter("cardNumber", cardNumber) :
                new ObjectParameter("cardNumber", typeof(string));
    
            var cvvParameter = cvv.HasValue ?
                new ObjectParameter("cvv", cvv) :
                new ObjectParameter("cvv", typeof(int));
    
            var dateOfExpiryParameter = dateOfExpiry.HasValue ?
                new ObjectParameter("dateOfExpiry", dateOfExpiry) :
                new ObjectParameter("dateOfExpiry", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_CheckAuthenticateTranscation", authtokenParameter, cardNumberParameter, cvvParameter, dateOfExpiryParameter);
        }
    }
}
